version: '3.8'
services:
  web: # 서비스 이름 : web
    #build: . # 디렉토리에 있는 Dockerfile을 사용하여 이미지를 생성
    image: 9uiopa/dworld:v1.3
    ports:
      - "80:8080" # 호스트의 80 포트를 컨테이너 8080포트와 연결
    environment:
      - SPRING_REDIS_HOST=redis # Redis 호스트 이름
      - SPRING_REDIS_PORT=6379 # Redis 포트 번호
    depends_on:
      - elasticsearch
      - redis
    restart: always
    networks:
      - app-network

  elasticsearch:
#    build: #로컬에서 별도 dockfile로 nori 포함된 es build
#      context: .
#      dockerfile: Dockerfile-es-nori
    image: 9uiopa/elasticsearch_nori
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    volumes: # 도커 볼륨
      - elasticsearchdb:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Redis 기본 포트
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  elasticsearchdb:
