version: '3.8'
services:
  web: # 서비스 이름 : web
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis # Redis 호스트 이름
      - SPRING_REDIS_PORT=6379 # Redis 포트 번호
    depends_on:
      - elasticsearch
      - redis
    restart: always
    networks:
      - app-network

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile-es-nori
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    volumes: # 도커 볼륨
      - elasticsearchdb:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Redis 기본 포트
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  elasticsearchdb:
