version: '3.8'
services:
  db: # 서비스 이름 : db
    image: mysql:8.0
    ports:
      - "3306:3306" # 로컬 3306 접근시 컨테이너 3306 port로 이동
    volumes: # 도커 볼륨
      - mysqldb:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
    restart: always

  web: # 서비스 이름 : web
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis # Redis 호스트 이름
      - SPRING_REDIS_PORT=6379 # Redis 포트 번호
    depends_on:
      - db
      - elasticsearch
      - redis
    restart: always
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:7.17.9
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    volumes: # 도커 볼륨
      - elasticsearchdb:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - app-network

  kibana:
    image: kibana:7.17.9
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Redis 기본 포트
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysqldb:
  elasticsearchdb:
