spring:
  profiles:
    active: dev  # 'dev' 프로파일 활성화
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" # {baseUrl} : 앱에서 사용하는 기본 주소 (http://localhost:8080 등)
            authorization-grant-type: authorization_code
            client-name: kakao # {registrationId}
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id           # 사용자 식별자 속성
  jpa:
    show-sql: true # 쿼리 확인
    defer-datasource-initialization: true #  데이터베이스 초기화 스크립트가 JPA 엔티티 설정이 완료된 후에 실행되도록
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # 로컬 db 스키마를 JPA 엔티티와 일치하도록 생성하거나 수정한다.

  elasticsearch:
    uris: http://elasticsearch:9200

  # 앱 실행시 sql 실행(data,schema.sql)
  sql:
    init:
      mode: always
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
  session:
    redis:
      repository-type: default
    timeout: 600 #세션 데이터 유효시간, 단위-초, 기본값 무한대

logging:
  level:
    org:
      springframework:
        security: INFO
        data:
          elasticsearch: INFO
      elasticsearch:
        client: INFO
    root: DEBUG